version: '3.8'

services:
  # Milvus Vector Database
  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus-standalone
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      - etcd
      - minio
    networks:
      - code-retrieval-network

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.0
    container_name: neo4j-standalone
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/neo4j
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - code-retrieval-network

  # etcd for Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: milvus-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - etcd_data:/etcd
    networks:
      - code-retrieval-network

  # MinIO for Milvus
  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - code-retrieval-network

volumes:
  milvus_data:
  neo4j_data:
  neo4j_logs:
  etcd_data:
  minio_data:

networks:
  code-retrieval-network:
    driver: bridge